---
.gitlab-ci.yml:
  delete: true

appveyor.yml:
  delete: true

Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'

Rakefile:
  changelog_user: puppetlabs
  extras:
    - |
      require 'rspec/core/rake_task'
      namespace :rook do
        RSpec::Core::RakeTask.new(:integration) do |t|
          t.pattern = 'spec/acceptance/**{,/*/**}/*_spec.rb'
          t.rspec_opts = "--tag integration"
        end
      end


.rubocop.yml:
  include_todos:
    inherit_from: '.rubocop_todo.yml'
  profiles:
    strict:
      configs:
        AllCops:
          TargetRubyVersion: '2.4'
          Exclude:
          - tooling/kube_tool/*
          - tooling/*
          - spec/defines/*
          - spec/classes/*
          - spec/*
          - spec/acceptance/*
          - rakelib/*
          - plans/*.pp
          - tasks/*

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
  hiera_config_ruby: File.expand_path(File.join(File.dirname(__FILE__), 'fixtures/hiera/hiera.yaml'))
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/pr_test.yml:
  unmanaged: true
.github/workflows/auto_release.yml:
  unmanaged: false
